name: CI

on: [push]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Composer update
        uses: nick-zh/composer@v0.2.0
        with:
          action: update
      - name:  Download cc-test-reporter
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/tmp/
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
          chmod +x ./tmp/cc-test-reporter
      - name: Start docker containers
        env:
          USER_ID: 1001
        run: cd ${GITHUB_WORKSPACE}/docker && docker-compose up -d
      - name: Run coverage
        run: cd ${GITHUB_WORKSPACE}/docker && docker-compose exec -T php make coverage
      - name: Upload coverage results to Code Climate
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: |
          ${GITHUB_WORKSPACE}/tmp/cc-test-reporter after-build -p /var/www/html --coverage-input-type clover;
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Composer update
        uses: nick-zh/composer@v0.2.0
        with:
          action: update
      - name: Start docker containers
        env:
          USER_ID: 1001
        run: cd ${GITHUB_WORKSPACE}/docker && docker-compose up -d
      - name: Run static analysis
        run: cd ${GITHUB_WORKSPACE}/docker && docker-compose exec -T php make static-analysis
  code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Composer update
        uses: nick-zh/composer@v0.2.0
        with:
          action: update
      - name: Start docker containers
        env:
          USER_ID: 1001
        run: cd ${GITHUB_WORKSPACE}/docker && docker-compose up -d
      - name: Check code style
        run: cd ${GITHUB_WORKSPACE}/docker && docker-compose exec -T php make code-style
